[project]
authors = ["Sina J. Semnani <sinaj@cs.stanford.edu>"]
channels = ["conda-forge", "main"]
description = "LEMONADE: A Large Multilingual Expert-Annotated Abstractive Event Dataset for the Real World"
name = "Lemonade"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = "3.12.*"  # Python version 3.12.x
pip = "*"          # Package installer for Python
redis = "*"        # In-memory data structure store, used for LLM caching
pre-commit = ">=4.2.0,<5"  # Git hooks framework for code quality checks

[pypi-dependencies]
chainlite = "==0.4.4"           # Unified interface for LLM API calls
json-repair = "*"               # JSON parsing and repair
orjsonl = "*"                   # Fast JSONL (JSON Lines) processing
rich = "*"                      # Rich text and beautiful formatting for terminal
loguru = "*"                    # Better logging
country-converter = ">=1.3, <2" # Country name/code conversion utilities
diskcache = ">=5.6.3, <6"       # Disk-based caching library. Used for caching geocoding results from nominatim.org
datasets = ">=3.6.0, <4"        # Hugging Face datasets library
black = "*"                     # Python code formatter
isort = "*"                     # Python import sorter
