[project]
authors = ["Sina J. Semnani <sinaj@cs.stanford.edu>"]
channels = ["pytorch", "nvidia", "conda-forge", "main", "r", "msys2"]
description = "LEMONADE: A Large Multilingual Expert-Annotated Abstractive Event Dataset for the Real World"
name = "Lemonade"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = "3.12.*"
pip = "*"
redis = "*"
pre-commit = ">=4.2.0,<5"

[pypi-dependencies]
chainlite = "==0.4.4"
json-repair = "*"
orjsonl = "*"
rich = "*"
loguru = "*"
black = "*"
isort = "*"
country-converter = ">=1.3, <2"
diskcache = ">=5.6.3, <6"
